# Версия Docker API
version: '3.7'

services:
  postgres_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: karmavdele
      POSTGRES_USER: postgres
      POSTGRES_DB: Sendji_006
    container_name: post_db

  online_store:
    build:
      context: ./
      dockerfile: Dockerfile
    command: bash -c "python manage.py makemigrations &&
             python manage.py migrate --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - postgres_db
    container_name: primary

volumes:
  postgres_data: