# Generated by Django 3.2.9 on 2021-11-05 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
